pythonwebservice/nwrsc/controllers/feed.py
"""
  This is the code for all the JSON and XML feeds.  Like the results interface, everything
  should be taken from the results table so that it continues to work after old series are
  expunged.  In general, JSON goes directly to the encoder, XML has to have some meta
  information posted in it to create meaningful tags (no anonymous lists or objects)
"""

import logging
from flask import Blueprint, request, g, escape, make_response
from nwrsc.lib.encoding import json_encode, json_raw, xml_encode
from nwrsc.model import Result, Settings 

log  = logging.getLogger(__name__)
Xml  = Blueprint("Xml", __name__)
Json = Blueprint("Json", __name__) 


@Json.route("/")
def jsoninfo():
    return json_raw(Result.getSeriesInfo(asstring=True))

@Xml.route("/")
def xmlinfo():
    info = Result.getSeriesInfo()
    info['_type'] = 'info'
    for x in info['challenges']: x['_type'] = 'Challenge'
    for x in info['events']:     x['_type'] = 'Event'
    for x in info['classes']:    x['_type'] = 'Class'
    for x in info['indexes']:    x['_type'] = 'Index'
    return xml_encode(dict(info)) # force back to base dict type


@Json.route("/<int:eventid>")
def jsonevent():
    return json_raw(Result.getEventResults(g.eventid, asstring=True))

@Xml.route("/<int:eventid>")
def xmlevent():
    res = Result.getEventResults(g.eventid)
    for entries in res.values():
        for e in entries:
            e['_type'] = 'Entrant'
            for c in e['runs']:
                for r in c:
                    r['_type'] = 'Run'
    return xml_encode(res, wrapper='classlist')


@Json.route("/champ")
def jsonchamp():
    return json_raw(Result.getChampResults(asstring=True))

@Xml.route("/champ")
def xmlchamp():
    res = Result.getChampResults()
    for y in res.values():
        for x in y: x['_type'] = 'ChampEntrant'
    res['_type'] = 'ChampClasses'
    return xml_encode(res)


@Json.route("/challenge/<int:challengeid>")
def jsonchallenge(challengeid):
    return json_encode(list(Result.getChallengeResults(challengeid).values()))

@Xml.route("/challenge/<int:challengeid>")
def xmlchallenge(challengeid):
    rounds = list(Result.getChallengeResults(challengeid).values())
    for rnd in rounds:
        rnd['_type'] = 'Round'
    return xml_encode(rounds, wrapper='Rounds')


@Xml.route("/<int:eventid>/scca")
def scca():
    results = Result.getEventResults(g.eventid)
    entries = list()
    for cls in results:
        for res in results[cls]:
            entries.append(dict(FirstName=res['firstname'],
                                 LastName=res['lastname'],
                                 MemberNo=res['membership'],
                                 Class=res['classcode'],
                                 Index=res['indexcode'],
                                 Pos=res['position'],
                                 CarModel="%s %s %s %s" % (res.get('year',''), res.get('make',''), res.get('model',''), res.get('color','')),
                                 CarNo="%s" % (res['number']),
                                 TotalTm="%0.3lf" % res['net'],
                                 _type='Entry'
                            ))
    return xml_encode(entries, wrapper="Entries")

pythonwebservice/nwrsc/controllers/mobile.py
import logging
import time
import urllib

from flask import Blueprint, abort, current_app, g, request, render_template
from nwrsc.lib.encoding import json_encode
from nwrsc.model import *
from nwrsc.lib.misc import csvlist

log = logging.getLogger(__name__)
Timer = Blueprint("Timer", __name__)
Announcer = Blueprint("Announcer", __name__) 

@Timer.route("/<float:lasttime>")
def timer(lasttime):
    """ Proxy this request to local data entry machine if we can """
    try :
        if current_app.config['SHOWLIVE']:
            f = urllib.request.urlopen("http://127.0.0.1:9090/timer/%0.3lf" % lasttime);
            return f.read()
        else:
            time.sleep(1)
            abort(403, "not an onsite server")

    except EnvironmentError as e:
        time.sleep(1) # slow down any out of control loops
        abort(404, e)
            

@Announcer.route("/")
def index():
    return "indexpage"

@Announcer.route("/<int:eventid>")
def base():
    g.event = Event.get(g.eventid)
    return render_template('/announcer/main.html')

@Announcer.route("/<int:eventid>/last")
def last():
    classes  = csvlist(request.args.get('classcodes',''))
    lasttime = request.args.get('time','2000-01-01')

    # Long polling, hold the connection until something is actually new
    then = time.time()
    while True:
        result = LastRun.getLast(g.eventid, lasttime, classes)
        if result != []:
            break
        if time.time() > then + 30:  # 30 second wait max to stop forever threads
            break
        time.sleep(0.8)

    return json_encode(result)

    
class AnnouncerController(object):

    def index(self):
        c.title = 'Scorekeeper Announcer'

        if self.eventid:
            c.javascript = ['/js/announcer.js']
            c.stylesheets = ['/css/announcer.css']
            c.event = self.event
            return render_mako('/announcer/main.mako')
        elif self.database is not None:
            c.events = self.session.query(Event).all()
            return render_mako('/results/eventselect.mako')
        else:
            return self.databaseSelector()

    def runorder(self):
        """
            Returns the HTML to render the NextToFinish box
        """
        c.order = loadNextRunOrder(self.session, self.event, int(request.GET.get('carid', 0)))
        return render_mako('/announcer/runorder.mako')


    #@jsonify
    def toptimes(self):
        """
            Returns the top times tables that are shown in the announer panel
        """
        carid = int(request.GET.get('carid', 0))
        ##data = self._toptimes(int(request.GET.get('carid', 0)))
        c.e2label = self.e2label

        ret = {}
        ret['updated'] = int(request.GET.get('updated', 0)) # Return it

        c.toptimes = self._loadTopTimes(carid, raw=False) #data['topnet']
        ret['topnet'] = render_mako('/announcer/topnettimes.mako').replace('\n', '')

        c.toptimes = self._loadTopTimes(carid, raw=True) #data['topraw']
        ret['topraw'] = render_mako('/announcer/toprawtimes.mako').replace('\n', '')

        if self.event.getSegmentCount() > 0:
            for ii in range(1, self.event.getSegmentCount()+1):
                c.toptimes = data['topseg%d' % ii]
                ret['topseg%d' % ii] = render_mako('/announcer/topsegtimes.mako').replace('\n', '')

        return ret


    def nexttofinish(self):
        nextid = getNextCarIdInOrder(self.session, self.event, int(request.GET.get('carid', 0)))
        return self._allentrant(nextid)

    def results(self):
        return self._allentrant(int(request.GET.get('carid', 0)))

    def _allentrant(self, carid):
        res = Result.getEventResults(g.eventid)
        ann = Result.getAnnouncerDetails(Settings.get(), res, carid)

        data = self._entrant(carid)
        c.event = self.event
        c.runs = data['runlist']
        c.results = data['classlist']
        c.champ = data['champlist']
        c.driver = self.driver
        c.cls = self.cls
        c.e2label = self.e2label
        
        ret = {}
        ret['updated'] = int(request.GET.get('updated', 0)) # Return it
        ret['entrantresult'] = render_mako('/announcer/entrant.mako').replace('\n', '')
        return ret


class LiveController(object):

    def index(self):
        if self.eventid:
            return self._browser()
        elif self.database is not None:
            return self._events()
        else:
            return self._database()


    def _database(self):
        c.dblist = self._databaseList(archived=False)
        return render_mako('/live/database.mako')

    def _events(self):
        c.events = self.session.query(Event).all()
        return render_mako('/live/events.mako')

    def _browser(self):
        c.event = self.event
        c.classes = [x[0] for x in self.session.query(Class.code).all()]
        return render_mako('/live/browser.mako')


    def Event(self):
        carid = int(self.routingargs.get('other', 0))
        c.results = self._classlist(carid)
        c.e2label = self.e2label
        return render_mako_def('/live/tables.mako', 'classlist')

    def Champ(self):
        carid = int(self.routingargs.get('other', 0))
        c.champ = self._champlist(carid)
        c.cls = self.cls
        c.e2label = self.e2label
        return render_mako_def('/live/tables.mako', 'champlist')

    def PAX(self):
        carid = int(self.routingargs.get('other', 0))
        c.e2label = self.e2label
        c.toptimes = self._loadTopTimes(carid, raw=False)
        return render_mako('/announcer/topnettimes.mako').replace('\n', '')

    def Raw(self):
        carid = int(self.routingargs.get('other', 0))
        c.e2label = self.e2label
        c.toptimes = self._loadTopTimes(carid, raw=True)
        return render_mako('/announcer/toprawtimes.mako').replace('\n', '')



CONVERT = {'old':'improvedon', 'raw':'couldhave', 'current':'highlight'}

class MobileController(object):

    def __before__(self):
        self.eventid = self.routingargs.get('eventid', None)
        try:
            self.eventid = int(self.eventid)
            self.event = self.session.query(Event).get(self.eventid)
        except (ValueError, TypeError):
            pass

    def _encode(self, head, o):
        response.headers['Content-type'] = 'text/javascript'
        return JEncoder(indent=1).encode(o)

    def index(self):
        if self.database is None:
            return self._encode("serieslist", self._databaseList())
        elif self.eventid is None:
            return self._encode("events", self.session.query(Event).all())
        elif self.eventid == 'classes':
            return self._encode("classes", self.session.query(Class).all())
        elif self.eventid == 'indexes':
            return self._encode("indexes", self.session.query(Index).all())
        else:
            return self._encode("nothing", [])


    def topnet(self):
        carid = int(self.routingargs.get('other', 0))
        return self._encode("toptimes", self._loadTopTimes(carid, False))


    def topraw(self):
        carid = int(self.routingargs.get('other', 0))
        return self._encode("toptimes", self._loadTopTimes(carid, True))


    def _loadTopTimes(self, carid, raw=False):
        classdata = ClassData(self.session)
        car = self.session.query(Car).get(carid)
        self.announcer = self.session.query(AnnouncerData).filter(AnnouncerData.eventid==self.eventid).filter(AnnouncerData.carid==carid).first()
        if self.announcer is None:
            raise BeforePage('')
        index = classdata.getEffectiveIndex(car)

        toptimes = TopTimesStorage(self.session, self.event, classdata)
        if raw:
            ret = self._convertTTS(toptimes.getList(allruns=False, raw=True, course=0), carid, self.announcer.oldsum/index, self.announcer.potentialsum/index)
        else:
            ret = self._convertTTS(toptimes.getList(allruns=False, raw=False, course=0), carid, self.announcer.oldsum, self.announcer.potentialsum)
        return ret


    def _convertTTS(self, tts, carid, oldsum, rawsum):
        position = 1
        additions = list()
        
        for entry in tts.rows:
            entry.position = position
            position += 1
            if entry.carid == carid:
                entry.label = 'current'
                if oldsum is not None and oldsum > 0:
                    additions.append(entry.copyWith(position='old', toptime=t3(oldsum), label='old'))
                if rawsum is not None and rawsum > 0:
                    additions.append(entry.copyWith(position='raw', toptime=t3(rawsum), label='raw'))

        if additions:
            tts.rows.extend(additions)
            tts.rows.sort(key=lambda x: float(x.toptime))
            tts.rows.sort(key=lambda x: int(x.courses), reverse=True)

        return tts.rows


    def _entrant(self, carid):
        return {
            'runlist': self._runlist(carid),
            'classlist': self._classlist(carid),
            'champlist': self._champlist(carid)
        }
        

    def runlist(self):
        carid = int(self.routingargs.get('other', 0))
        return self._encode("runlist", self._runlist(int(carid)))

    def _runlist(self, carid):
        self.announcer = self.session.query(AnnouncerData).filter(AnnouncerData.eventid==self.eventid).filter(AnnouncerData.carid==carid).first()
        if self.announcer is None:
            raise BeforePage('no announcer data')

        query = self.session.query(Run).filter(Run.carid==carid).filter(Run.eventid==self.eventid)
        query = query.filter(Run.course==self.announcer.lastcourse).filter(Run.course==self.announcer.lastcourse).order_by(Run.run)
        runs = query.all()
        if self.announcer.rawdiff:
            runs[-1].rawdiff = self.announcer.rawdiff
        if self.announcer.netdiff:
            runs[-1].netdiff = self.announcer.netdiff
        for r in runs:
            if r.norder == 1: r.label = 'current'

pythonwebservice/nwrsc/templates/results/champ.html
{% extends "results/rbase.html" %}

{% block content %}
<!-- Series info -->
<div id='seriestitle'>{{settings.seriesname}}</div>
{% if settings.minevents > 0 %}
<div id='minwarning'>(Min Attendance of {{settings.minevents}} Events To Place)</div>
{% endif %}
<hr />
<!-- Results -->

<table class='champ'>
{% for code, entrants in results.items()|sort %}
{% set cls = classdata.classlist[code] %}

<tr class='classhead'><th colspan='{{events|length + 4}}'>{{cls.classcode}} - {{cls.descrip}} -
            Average Per Event: {{"%.2lf"%(entrants.entries/(events|length))}}</th></tr>
<tr>
<th>#</th>
<th>Name</th>
<th>Attended</th>
{% for event in events %}
<th>Event {{loop.index}}</th>
{% endfor %}
<th>Total</th>
</tr>
        
{% for e in entrants %}
	{% if e.eventcount < settings.minevents %}
	<tr class='missingmin'>
	{% else %}
	<tr>
	{% endif %}
    <td>{{e.position}}</td>
    <td class='name'>{{e.firstname}} {{e.lastname}}</td>
    <td class='attend'>{{e.eventcount}}</td>
    {% for event in events %}
		{% set key = "d-"+event.date %}
        <td class='points {{key in e.points.drop and "drop" or ""}}'>{{e.points.events[key]|t3}}</td>
    {% endfor %}
    <td class='points'>{{e.points.total|t3}}</td>
    </tr>
{% endfor %}
{% endfor %}
</table>
{% endblock content %}

pythonwebservice/nwrsc/templates/results/classresult.html
{% extends "base.html" %}
{% set colcount = 6 + g.event.runs %}
{% set rowspan = "rowspan='%s'" % (g.event.courses) %}

{% block headers %}
<link rel="stylesheet" href="/static/results.css" />
{% endblock %}

{% block content %}
{% if ispost %}
	{{eventpost()}}
{% else %}
	{{resulttables()}}
{% endif %}
{% endblock content %}


{% macro eventpost() %}
<!-- Series info -->
<div id='seriescustom'>
{{g.settings.customheader|safe}}
</div>

<div id='seriestitle'>{{g.settings.seriesname}}</div>

<!-- Event info -->
<div id='eventtitle'>{{g.event.date}} - {{g.event.name}}</div>
<div id='hosttitle'>Hosted At: <span class='host'>{{g.event.attr.location}}</span></div>
<div id='entrantcount'>({{g.entrantcount}} Entrants)</div>

<hr />
<!-- Results -->

<div id='classlinks'>
{% for cls in g.results|sort -%}
<a href='#{{cls}}'>{{cls}}</a>
{% endfor %}
</div>

{{resulttables()}}

<br/>
<br/>
{# ${toptimestable([c.toptimes.getList(allruns=False, raw=False, course=0), c.toptimes.getList(allruns=False, raw=True, course=0)])} #}
{% endmacro %}



{% macro resulttables() -%}
<table class='classresults'>
{% for code,entrants in g.results.items()|sort %}
	{{headerrow(code)}}
	{% for e in entrants %}
		{{entrantrow(e)}}
		{%- for runs in e.runs[1:] -%}
			<tr>
			{% for run in runs -%}
				{{runcell(run)}}
            {%- endfor -%}
			</tr>
        {%- endfor -%}
    {% endfor %}
{% else %}
    No results found
{% endfor %}
</table>
{%- endmacro %}



{% macro headerrow(classcode) -%}
<tr>
	<th class='classhead' colspan='{{colcount}}'>
	<a name='{{classcode}}'>{{classcode}}</a> - {{descrip}}
	</th>
</tr>
<tr>
<th class='pos'>#</th>
<th class='trophy'>T</th>
<th class='name'>Entrant</th>
{% for ii in range(1, g.event.runs+1) -%}
	<th class='run'>Run {{ii}}</th>
{% endfor %}
<th></th>  {# Extra col to fix firefox border bug #}
<th class='total'>Total</th>
<th class='points'>Points</th>
</tr>
{%- endmacro %}



{%- macro entrantrow(entrant) %}
<tr class='entrantrow'>
	<td class='pos' {{rowspan|safe}}>{{entrant.position}}</td>
	<td class='trophy' {{rowspan|safe}}>{{entrant.trophy and 'T' or ''}}</td>
	<td class='name' align='center' {{rowspan|safe}}>#{{entrant.number}} - {{entrant.firstname}} {{entrant.lastname}}<br/>
		{{entrant.make}} {{entrant.model}} {{entrant.color}} {{entrant.indexstr and "(%s)"%entrant.indexstr or ""}}</td>
	{% for run in entrant.runs[0] -%}
		{{runcell(run)}}
	{%- endfor %}
	<td {{rowspan|safe}}></td> {# Extra col to fix firefox border bug #}
	<td class='total' {{rowspan|safe}}>{{entrant.sum | t3}}</td>
	<td class='points' {{rowspan|safe}}>{{entrant.points | t3}}</td>
	{# Can reference entrant.pospoints or entrant.diffpoints to bypass series setting for points type #}
</tr>
{% endmacro %}



{%- macro runcell(run) %}
{%- if not run -%}
<td class='run'>
blank
{%- else -%}
<td class='run {{run.bestnet and "bestnet"}} {{run.bestraw and "bestraw"}}'>
{%- if run.status == "OK" -%}
	<span class='net'>{{run.net | t3}}</span>
{%- else -%}
	<span class='net'>{{run.status}}</span>
{%- endif -%}
{%- if run.raw != "999.999" -%} <span class='raw'>{{run.raw | t3}} ({{run.cones}},{{run.gates}})</span> {%- endif -%}
{%- if run.reaction or run.sixty -%} <span class='reaction'>{{run.reaction|t3}}/{{run.sixty | t3}}</span> {%- endif -%}
{%- endif -%}
</td>
{% endmacro -%}

pythonwebservice/nwrsc/templates/results/event.html
{% extends "base.html" %}

{% block headers %}
{{ super() }}

<style type="text/css">
ul, ol, h3, h2 { text-align: left; }
h3 { color: #111; margin-bottom: 0px; }
ul { margin-top: 0px; list-style: none; }
a { color: #44A; text-decoration: none; }

ul.classlist {
margin: 0;
margin-left: 40px;
padding: 0;
list-style: none;
width: 350px;
}

ul.classlist li {
float: left;
width: 70px;
margin: 0;
padding: 0;
}
</style>

{% endblock headers %}


{% block content %}
{{ super() }}

<h2>Results for {{g.event.name}}</h2>

<h3>Active Classes</h3>
<ul class='classlist'>
{% for cls in g.active %}
	<li><a href='{{url_for('.byclass', list=cls.classcode)}}'>{{cls.classcode}}</a></li>
{% endfor %}
</ul>
<br style='clear:both;'/>

<h3>Classes By Run Group</h3>
<ul class='classlist'>
{% for ii in range(1,5) %}
	<li><a href='{{url_for('.bygroup', list=ii)}}'>R{{ii}}</a></li>
{% endfor %}
</ul>
<br style='clear:both;'/>

{%if g.event.ispro %}
	{%for ch in g.challenges %}
		<h3>{{ch.name}}</h3>
		<ul class='classlist'>
		<li><a href='{{url_for('.bracket', challengeid=ch.challengeid)}}'>Bracket</a></li>
		<li><a href='{{url_for('.challenge', challengeid=ch.challengeid)}}'>Details</a></li>
		</ul>
		<br style='clear:both'/>
	{%else%}
        <!-- No challenges created yet. -->
    {%endfor%}
{%endif%}

<h3>Top Times Lists (All Runs)</h3>
<ul class='classlist'>
<li><a href='{{url_for('.tt', tttype='indexall')}}'>Indexed</a></li>
<li><a href='{{url_for('.tt', tttype='rawall')}}'>Raw</a></li>
</ul>
<br style='clear:both;'/>


<h3>Top Times Lists (Counted Runs)</h3>
<ul class='classlist'>
<li><a href='{{url_for('.tt', tttype='index')}}'>Indexed</a></li>
<li><a href='{{url_for('.tt', tttype='raw')}}'>Raw</a></li>
</ul>
<br style='clear:both;'/>


{%if g.event.getSegmentCount() > 0 %}
<h3>Other Top Times Lists</h3>
<ul class='classlist'>
<li><a href='{{url_for('.tt', tttype='seg')}}'>Segment</a></li>
</ul>
<br style='clear:both;'/>
{% endif %}


<h3>Other</h3>
<ul>
{%if config.SHOWLIVE %}
<li><a href="{{url_for('Live.index')}}">Mobile Live Page</a></li>
<li><a href="{{url_for('Announcer.index')}}">Announcer Panel</a></li>
{% endif %}
<li><a href='{{url_for('.post')}}'>Event Results</a></li>
<li><a href='{{url_for('.champ')}}'>Championship</a></li>
<li><a href='{{url_for('Xml.scca')}}'>SCCA Report</a></li>

{%if g.event.ispro and config.SHOWGRID %}
	<li><a href='{{url_for('.grid', order='number')}}'>Grid By Number</a></li>
	<li><a href='{{url_for('.grid', order='position')}}'>Grid By Position</a></li>
{% endif %}
{%if g.event.ispro %}
	<li><a href='{{url_for('.dialins', order='net')}}'>Dialins By Net</a></li>
	<li><a href='{{url_for('.dialins', order='diff')}}'>Dialins By Diff</a></li>
{% endif %}
</ul>

{% endblock content %}

pythonwebservice/nwrsc/templates/results/eventindex.html
{% extends "/results/rbase.html" %}

{% block headers %}
{{ super() }}

<style type="text/css">
ul, ol, h3, h2 { text-align: left; }
h3 { color: #111; margin-bottom: 0px; }
ul { margin-top: 0px; list-style: none; }
a { color: #44A; text-decoration: none; }

ul.classlist {
margin: 0;
margin-left: 40px;
padding: 0;
list-style: none;
width: 350px;
}

ul.classlist li {
float: left;
width: 70px;
margin: 0;
padding: 0;
}


.matrix {
	margin: 20px;
	border-collapse: collapse;
}
.matrix td, .matrix th {
	padding: 4px;
	text-align: center;
	border: 1px solid grey;
	background: none;
}

</style>

{% endblock headers %}


{% block content %}
{{ super() }}

<h2>Results for {{event.name}}</h2>

<h3>Active Classes</h3>
<ul class='classlist'>
{% for code in active|sort %}
	<li><a href='{{url_for('.byclass', list=code)}}'>{{code}}</a></li>
{% endfor %}
</ul>
<br style='clear:both;'/>

<h3>Classes By Run Group</h3>
<ul class='classlist'>
{% for ii in range(1,5) %}
	<li><a href='{{url_for('.bygroup', list=ii)}}'>R{{ii}}</a></li>
{% endfor %}
</ul>
<br style='clear:both;'/>

{%if event.ispro %}
	{%for ch in challenges %}
		<h3>{{ch.name}}</h3>
		<ul class='classlist'>
		<li><a href='{{url_for('.bracket', challengeid=ch.challengeid)}}'>Bracket</a></li>
		<li><a href='{{url_for('.challenge', challengeid=ch.challengeid)}}'>Details</a></li>
		</ul>
		<br style='clear:both'/>
	{%else%}
        <!-- No challenges created yet. -->
    {%endfor%}
{%endif%}

<h3>Top Times Lists</h3>
<table class='matrix'>
<tr>
	<th></th>
	<th>Counted Runs</th>
	<th>All Runs</th>
</tr>
<tr>
	<th>Indexed</th>
	<td><a href='{{url_for('.tt', indexed=1, counted=1)}}'>List</a></td>
	<td><a href='{{url_for('.tt', indexed=1, counted=0)}}'>List</a></td>
</tr>
<tr>
	<th>Unindexed</th>
	<td><a href='{{url_for('.tt', indexed=0, counted=1)}}'>List</a></td>
	<td><a href='{{url_for('.tt', indexed=0, counted=0)}}'>List</a></td>
</tr>
{%if event.segments > 1 %}
<tr>
	<th>Segments</th>
	<td colspan=2><a href='{{url_for('.tt', indexed=0, counted=0, segments=1)}}'>List</a></td>
</tr>
{% endif %}
</table>

<h3>Other</h3>
<ul>
{%if config.SHOWLIVE %}
{# FINISH ME <li><a href="{{url_for('Live.index')}}">Mobile Live Page</a></li> #}
<li><a href="{{url_for('Announcer.index')}}">Announcer Panel</a></li>
{% endif %}
<li><a href='{{url_for('.post')}}'>Event Results</a></li>
<li><a href='{{url_for('.champ')}}'>Championship</a></li>
<li><a href='{{url_for('Xml.scca')}}'>SCCA Report</a></li>

{%if event.ispro %}
	<li><a href='{{url_for('.dialins', order='net')}}'>Dialins By Net Time</a></li>
	<li><a href='{{url_for('.dialins', order='prodiff')}}'>Dialins By Class Diff</a></li>
{% endif %}
</ul>

{% endblock content %}

pythonwebservice/nwrsc/templates/results/eventlist.html
{% extends "/results/rbase.html" %}

{% block headers %}
{{ super() }}
<style>
h2 { text-align: left; }
ul { list-style: none; }
</style>

{% endblock headers %}

{% block content %}
<h2>Select Event:</h2>
<ul>
{% for e in events %}
	<li><a href='{{url_for('.event', eventid=e.eventid)}}'>{{e.name}}</a></li>
{% endfor %}
<li>&nbsp;</li>
<li><a href='{{url_for('.champ')}}'>Championship</a></li>
</ul>
{% endblock content %}

pythonwebservice/nwrsc/templates/results/eventresults.html
{% extends "/results/rbase.html" %}
{% import '/results/ttmacros.html' as tt %}
{% if g.event.ispro %}
{% import '/results/promacros.html' as res %}
{% else %}
{% import '/results/macros.html' as res %}
{% endif %}

{% block content %}
{% if not ispost %}

<h2>{{g.title}}</h2>
{{res.classtables(results)}}

{% else %}

<!-- Series info -->
<div id='seriescustom'>
{{g.settings.customheader|safe}}
</div>

<div id='seriestitle'>{{g.settings.seriesname}}</div>

<!-- Event info -->
<div id='eventtitle'>{{g.event.date}} - {{g.event.name}}</div>
<div id='hosttitle'>Hosted At: <span class='host'>{{g.event.location}}</span></div>
<div id='entrantcount'>({{g.entrantcount}} Entrants)</div>

<hr />
<!-- Results -->

<div id='classlinks'>
{% for cls in results|sort -%}
<a href='#body{{cls}}'>{{cls}}</a>
{% endfor %}
</div>

{{res.classtables(results)}}
<br/>
<br/>
{{tt.toptimestable(g.toptimes)}}

{% endif %}
{% endblock content %}

pythonwebservice/nwrsc/templates/results/rbase.html
{% extends "base.html" %}
{% block headers %}
{%- assets filters="libsass,cssmin", output="results.css", "scss/results.scss" -%}
<link rel="stylesheet" href="{{ASSET_URL}}" /> 
{%- endassets -%}
{% endblock %}